# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        movies:
            types:
                movie:
                    indexable_callback: ['App\Service\Search\Elastic', 'isIndexMovie']
                    properties:
                        imdb: ~
                        title: ~
                        genres: ~
                        #synopsis: ~
                        existTranslations: ~
                        locales:
                            type: "nested"
                            properties:
                                locale: ~
                                title: ~
                                #synopsis: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Movie
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                        listener: ~
        shows:
            types:
                show:
                    indexable_callback: ['App\Service\Search\Elastic', 'isIndexShow']
                    properties:
                        imdb: ~
                        title: ~
                        genres: ~
                        #synopsis: ~
                        existTranslations: ~
                        locales:
                            type: "nested"
                            properties:
                                locale: ~
                                title: ~
                                #synopsis: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Show
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                        listener: ~
