sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
            level: error
    options:
        error_types: E_ALL
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException

monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
