- name: Nginx site conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/popcorn.conf
    mode: '0644'
  notify:
    - restart nginx

- name: Nginx cache folder
  file:
    dest: "{{ path }}/var/nginx"
    state: directory
    mode: '0666'

- name: delete php fpm default pool
  file:
    path: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    state: absent
  notify:
    - restart php-fpm

- name: php fpm pool
  template:
    src: pool.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/popcorn.conf
    mode: '0644'
  notify:
    - restart php-fpm

- name: user cron config
  template:
    src: crontab.j2
    dest: /var/spool/cron/crontabs/{{ user }}
    owner: '{{ user }}'
    group: 'crontab'
    mode: '0600'
  notify:
    - restart cron

- name: logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/popcorn
    mode: '0644'
